import React, { useEffect, useMemo, useState } from "react";
import metfpaApi from "@/lib/metfpaApi";
import { apiError, pct, Pill, PRIORITY_COLORS, statusLabel, STATUS_COLORS } from "@/lib/operational";
import { Breadcrumb } from "@/components/Breadcrumb";
import { DemoBanner } from "@/components/DemoBanner";
import { AlertTriangle, GitMerge, Loader2 } from "lucide-react";

export default function Alignement() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const [filters, setFilters] = useState({ pnd_axis: "", objective: "", program: "", direction: "", status: "", priority: "", risk: "" });
  useEffect(() => { metfpaApi.get("/pnd-alignment").then((r) => setData(r.data)).catch((e) => setError(apiError(e))); }, []);
  const options = useMemo(() => { const rows = data?.items || []; const uniq = (k) => [...new Set(rows.map((x) => x[k]).filter(Boolean))].sort(); return { pnd_axis: uniq("pnd_axis"), objective: uniq("strategic_objective"), program: uniq("budget_program"), direction: uniq("direction"), status: uniq("status"), priority: uniq("priority"), risk: uniq("risk_level") }; }, [data]);
  const rows = useMemo(() => (data?.items || []).filter((x) => (!filters.pnd_axis || x.pnd_axis === filters.pnd_axis) && (!filters.objective || x.strategic_objective === filters.objective) && (!filters.program || x.budget_program === filters.program) && (!filters.direction || x.direction === filters.direction) && (!filters.status || x.status === filters.status) && (!filters.priority || x.priority === filters.priority) && (!filters.risk || x.risk_level === filters.risk)), [data, filters]);
  return <div className="space-y-6 animate-slide-up" data-testid="page-alignement"><Breadcrumb items={[{ label: "Alignement PND" }]} /><DemoBanner />
    <div className="bg-white rounded-[8px] border border-[var(--border)] p-6"><div className="text-[11px] uppercase tracking-[0.12em] font-semibold text-[var(--ci-green-700)]"><GitMerge size={13} className="inline mr-1" /> Chaîne de responsabilité</div><h1 className="text-2xl font-bold mt-1">Alignement PND → Mission → Direction</h1><div className="flex flex-wrap gap-1.5 mt-4">{(data?.chain || ["PND","Axe","Objectif sectoriel","Programme budgétaire","Mission","Direction","Statut","Avancement"]).map((c, i, a) => <React.Fragment key={c}><span className="text-xs px-2 py-1 rounded-[5px] bg-[var(--surface-soft)] border">{c}</span>{i < a.length - 1 && <span className="text-[var(--ink-500)]">→</span>}</React.Fragment>)}</div></div>
    {error ? <div className="p-5 bg-white border rounded-[8px] text-[#C93C37]"><AlertTriangle size={15} className="inline mr-2" />{error}</div> : !data ? <Loader2 className="animate-spin mx-auto" /> : <><div className="bg-white border rounded-[8px] p-4 flex flex-wrap gap-3">{Object.entries({ pnd_axis: "Axe PND", objective: "Objectif", program: "Programme", direction: "Direction", status: "Statut", priority: "Priorité", risk: "Risque" }).map(([key, label]) => <label key={key}><span className="text-[11px] font-semibold text-[var(--ink-500)]">{label}</span><select value={filters[key]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })} className="block mt-1 max-w-[220px] rounded-[6px] border px-2 py-2 text-sm bg-white"><option value="">Tous</option>{options[key].map((o) => <option key={o} value={o}>{key === "status" ? statusLabel(o) : o}</option>)}</select></label>)}<span className="ml-auto self-end text-xs text-[var(--ink-500)] pb-2">{rows.length} mission(s)</span></div><div className="bg-white border rounded-[8px] overflow-x-auto"><table className="w-full text-sm" data-testid="pnd-alignment-table"><thead className="bg-[var(--surface-soft)] text-[11px] uppercase text-[var(--ink-500)]"><tr>{["PND","Axe","Objectif sectoriel","Programme budgétaire","Mission / action","Direction","Statut","Avancement","Priorité","Risque"].map((h) => <th key={h} className="text-left px-3 py-2.5 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.id} className="border-t"><Td>{r.pnd_pillar}</Td><Td>{r.pnd_axis || "Manquant"}</Td><Td>{r.strategic_objective || "Manquant"}</Td><Td>{r.budget_program || "Manquant"}</Td><Td wide>{r.action_title}</Td><Td>{r.direction || "Manquante"}</Td><Td><Pill label={statusLabel(r.status)} color={STATUS_COLORS[r.status]} /></Td><Td>{pct(r.progress)}</Td><Td><Pill label={r.priority} color={PRIORITY_COLORS[r.priority]} /></Td><Td>{r.risk_level}</Td></tr>)}</tbody></table></div></>}
  </div>;
}
function Td({ children, wide }) { return <td className={`px-3 py-3 align-top ${wide ? "min-w-[280px]" : "max-w-[220px]"}`}>{children}</td>; }
