import React, { useEffect, useState } from "react";
import metfpaApi from "@/lib/metfpaApi";
import { apiError, pct } from "@/lib/operational";
import { Breadcrumb } from "@/components/Breadcrumb";
import { DemoBanner } from "@/components/DemoBanner";
import { toast } from "sonner";
import { AlertTriangle, Building2, Download, FileText, Gavel, Loader2 } from "lucide-react";

export default function Reporting() {
  const [data, setData] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { metfpaApi.get("/director-dashboard").then((r) => setData(r.data)).catch((e) => setError(apiError(e))); }, []);
  const pdf = async () => { setBusy(true); try { const r = await metfpaApi.get("/cabinet/export/pdf?note=Reporting%20hebdomadaire%20DIRCAB", { responseType: "blob" }); const url = URL.createObjectURL(new Blob([r.data], { type: "application/pdf" })); const a = document.createElement("a"); a.href = url; a.download = `Reporting_DIRCAB_${new Date().toISOString().slice(0,10)}.pdf`; a.click(); URL.revokeObjectURL(url); toast.success("Reporting PDF généré"); } catch (e) { toast.error(apiError(e)); } finally { setBusy(false); } };
  return <div className="space-y-6 animate-slide-up" data-testid="page-reporting"><Breadcrumb items={[{ label: "Reporting" }]} /><DemoBanner />
    <div className="bg-white border rounded-[8px] p-6 flex justify-between gap-4"><div><div className="text-[11px] uppercase tracking-[0.12em] font-semibold text-[var(--ci-green-700)]"><FileText size={13} className="inline mr-1" /> Sortie hebdomadaire</div><h1 className="text-2xl font-bold mt-1">Reporting DIRCAB</h1><p className="text-sm text-[var(--ink-700)] mt-2">Prévisualisation structurée à partir des mêmes données que la Vue Directeur.</p></div><button onClick={pdf} disabled={busy} className="self-start px-3.5 py-2 rounded-[6px] bg-[var(--ink-900)] text-white text-sm font-semibold inline-flex gap-1.5">{busy ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}Générer le PDF</button></div>
    {error ? <div className="p-5 bg-white border rounded-[8px] text-[#C93C37]">{error}</div> : !data ? <Loader2 className="animate-spin mx-auto" /> : <><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Card label="Exécution globale" value={pct(data.summary.execution_rate)} icon={FileText} /><Card label="Retards" value={data.summary.missions_overdue} icon={AlertTriangle} danger /><Card label="Décisions en attente" value={data.summary.decisions_pending} icon={Gavel} /><Card label="Directions à relancer" value={data.summary.directions_stale} icon={Building2} danger /></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><ReportSection title="Résumé exécutif"><p className="text-sm leading-relaxed">{data.summary.missions_total} missions suivies, avec un taux d'exécution global de {pct(data.summary.execution_rate)}. {data.summary.missions_overdue} mission(s) sont en retard et {data.summary.critical_blockers} blocage(s) critiques nécessitent une attention du Cabinet.</p></ReportSection><ReportSection title="Décisions"><List items={[...data.decisions_this_week, ...data.decisions_this_month].slice(0,8)} render={(x) => x.title} /></ReportSection><ReportSection title="Points à arbitrer"><List items={data.what_blocks} render={(x) => `${x.code} · ${x.blocker || x.action_title}`} /></ReportSection><ReportSection title="Directions à relancer"><List items={data.directions_to_follow_up} render={(x) => `${x.direction} · score de mise à jour ${x.update_score}/100`} /></ReportSection><ReportSection title="Actions de la semaine"><List items={data.top_priority_missions} render={(x) => `${x.code} · ${x.action_title} · ${x.progress}%`} /></ReportSection><ReportSection title="Prochaine réunion"><p className="text-sm">{data.next_meeting.title}</p><p className="text-xs text-[var(--ink-500)] mt-1">{data.proposed_agenda.length} point(s) proposés automatiquement.</p></ReportSection></div></>}
  </div>;
}
function Card({ label, value, icon: Icon, danger }) { return <div className="bg-white border rounded-[8px] p-4"><Icon size={16} className={danger ? "text-[#C93C37]" : "text-[var(--ci-green-700)]"} /><div className="text-2xl font-bold mt-2">{value}</div><div className="text-xs text-[var(--ink-500)]">{label}</div></div>; }
function ReportSection({ title, children }) { return <section className="bg-white border rounded-[8px] p-5"><h2 className="font-semibold text-sm mb-3">{title}</h2>{children}</section>; }
function List({ items, render }) { return items.length ? <ul className="space-y-2">{items.map((x, i) => <li key={x.id || x.direction || i} className="text-sm border-b last:border-0 pb-2">{render(x)}</li>)}</ul> : <p className="text-sm text-[var(--ink-500)] italic">Aucun élément.</p>; }
